spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  servlet:
    contextPath: /cpps-log
    application-display-name: cpps-log
    session:
      timeout: 960m
path_to_print: ${PATH_TO_PRINT}